### PR TITLE
Firmware: Adding BQ Hephestos 2

### PR DESCRIPTION
**Pull request by thopiekar**
Asked for this a while ago in BQ's forums, but no reaction.
- http://www.bq.com/de/support/hephestos-2

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
That's awesome. Two things though:
* Where did you get the source from, so I can try to reproduce your build? I know that you can be trusted, but it's still unwise to publish binary data from an unknown source in a project that claims to be open source. I'd like to compare hashes.
* This needs an entry in USBPrinterManager.py to become functional, even though USBPrinterManager is about to lose the firmware update functionality. When we're moving the functionality, it's useful to have a list of all the firmware updates we provide in that file.

**Comment by thopiekar** [comment]
These firmware files are taken from the support page at BQ for my printer.
So they precompiled.
Is there a reason why we need to build it from source?
I've got a link somewhere with a guide by BQ - Just have to take a look for
it when I'm back home.

**Comment by Ghostkeeper** [comment]
Well, it's including third-party binaries. I'd like to be at least sort-of sure that nothing has meddled with the binaries.

Looks like the firmware is over here: https://github.com/bq/Marlin
I suppose that the BQ website itself can be considered a "trusted source". Maybe we'll have to, if the binaries differ due to different compiler versions, firmware version, or settings...

**Comment by Ghostkeeper** [comment]
I tried downloading the hex file from BQ's website and got no diff. That's where you got it from so that's correct. But I also tried compiling BQ's Marlin version and got vastly different files. I expected only the timestamp to be different.

I am communicating with BQ to find out how to get those binaries correct, because we have to be able to provide the source code it was compiled with for our (and Marlin's) license.

**Comment by daid** [comment]
@Ghostkeeper if you just take the binary from QB, you can state that they have to provide the source code. (There should be something in GPL about unmodified binaries I think)
Note that the hex file will differ depending on the compiler, arduino version and OS used.

**Comment by Ghostkeeper** [comment]
It will also differ due to the timestamp. I have the same Arduino version as them now (it mentions the Arduino version in their readme). I have inquired about their OS and compiler version.

**Pull request closed without merging**
