### PR TITLE
Windows: Updating Arduino drivers

### PR DESCRIPTION
**Pull request by thopiekar**
These are the Arduino drivers found in zip archive of the 1.6.12
release.
Beleaving the README the drivers are signed for Windows 8 (therefore
also for newer versions?!). However, I have not installed them
currently, just to be sure, that our installer will replace the
preinstalled drivers provided by Windows.

Contributes to CURA-2713

### CODE REVIEW

**Comment by thopiekar** [comment]
ping

**Comment by Ghostkeeper** [comment]
Where did you source these files? I'd like to check their integrity.

**Comment by thopiekar** [comment]
From an Arduino IDE installation, but don't ask me which release :yum:

**Comment by Ghostkeeper** [comment]
Devs, see issue CURA-4226.

**Comment by LipuFei** [comment]
It has been a while, shall we update the drivers again from arduino 1.8.5?

**Comment by Ghostkeeper** [comment]
Maybe we'll have to do that in a different PR though.

**Comment by thopiekar** [comment]
Updated the drivers

**Comment by Ghostkeeper** [comment]
I'm checking file integrity. These are my findings when comparing to the driver subdirectory of the Windows Zip file of Arduino 1.8.5: https://www.arduino.cc/download_handler.php?f=/arduino-1.8.5-windows.zip

My findings of the differences:
* The folder CP210x_6.7 is missing. This seems to be superseded by CP210x_6.7.4 though (which is present in both).
* Some of the line feeds were LF instead of CRLF, in AdafruitCircuitPlayground.inf, arduino.inf, genuino.inf and in CP210x_6.7.4/slabvcp.inf. This is probably because of Git.

So if the Arduino.cc website is to be trusted, I will vouch for these binaries' safety.

**Comment by ChrisTerBeke** [comment]
Arduino.cc is totally OK with me :)

**Comment by thopiekar** [comment]
Wohoo, finally approved 😄 🎉

**Comment by LipuFei** [comment]
@thopiekar There is something wrong with the driver. If you install manually with `dpinst-amd64.exe`, some of the components won't be installed successfully. But with the official driver from Arduino 1.8.5, there is no such problem.

image

**Comment by thopiekar** [comment]
Can you reproduce it on a fresh Windows installation? Or on a different computer?

Thanks

**Comment by LipuFei** [comment]
We can reproduce this on a different Windows machine in the office, failing on the same components as shown in the screenshot.

**Comment by thopiekar** [comment]
Are you sure about the FTDI drivers, they should be there:
https://github.com/thopiekar/cura-binary-data/tree/master-CURA-2713-clean/windows/arduino/FTDI%20USB%20Drivers

**Comment by LipuFei** [comment]
@thopiekar I found the problem: you committed using the UNIX End-of-Lines. This doesn't work on Windows. I will merge this PR and fix that for you.

**Pull request merged**
